<style>
    :root{
        /** Colors */
        --snow: #F5F5F5;
        --dark-snow: #E4E4E4;
        --smoke: #787878;
        --gray: #404040;
        --gray2: #DDD;
        --black: #1E1E1E;

        --brightness: hsl(0deg 0% 100%);
        --highlight: #0b8793;
        --midtone: #BBB;
        --shadow: #360033;
        --darkness: hsl(0deg 0% 11%);

        /** Typography */
        --root-font: 'Raleway', sans-serif;
        --root-font-size: 16px;
    }
</style>
