<style>
    :root{
        /** Colors */
        --snow: #b5b5b5;
        --smoke: #717271;
        --black: #1E1E1E;
        --white: #FFFFFF;

        --brightness: hsl(0deg 0% 100%);
        --darkness: hsl(0deg 0% 11%);

        --primary: #360033;
        --primary-dark: #18000e;
        --primary-light: #622b5d;
        --secondary: #0b8893;
        --secondary-dark: #005b65;
        --secondary-light: #53b8c3;

        --error: #B00020;
        --warning: #faad14;
        --success: #52c41a;

        /** Typography */
        --root-font: 'Raleway', sans-serif;
        --root-font-size: 16px;

        /** Forms */
        --input-radius: 0;
        --input-background: var(--darkness);
        --input-border: var(--snow);
        --input-font-color: var(--smoke);
        --input-placeholder-color: var(--smoke);
    }
</style>
